---
abstract: 'a role providing a locally cached copy of a remote file'
author:
  - 'Neil Bowers <neil@bowers.com>'
build_requires:
  File::Touch: '0'
  Moo: '0'
  Test::File: '0'
  Test::More: '0.88'
  autodie: '0'
  lib: '0'
  strict: '0'
  warnings: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.015, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MooX-Role-CachedURL
requires:
  Carp: '0'
  File::HomeDir: '0'
  File::Spec::Functions: '0'
  HTTP::Tiny: '0'
  Moo::Role: '0'
  PerlIO::gzip: '0'
  Time::Duration::Parse: '0'
  perl: '5.006'
resources:
  homepage: https://github.com/neilbowers/MooX-Role-CachedURL
  repository: https://github.com/neilbowers/MooX-Role-CachedURL.git
version: '0.06'
